apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crewai
  template:
    metadata:
      labels:
        app: crewai
    spec:
      containers:
        - name: crewai
          image: abdullah122/crewai_app:latest  
          imagePullPolicy: Always  
          ports:
            - containerPort: 5000
          env:
            - name: OLLAMA_API_BASE
              value: "http://ollama:11434"
          command: ["python3", "api.py"]
          livenessProbe: 
            httpGet:
              path: /health  # Update if your app has a health endpoint
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe: 
            httpGet:
              path: /health  # Update if needed
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
      restartPolicy: Always  # Ensures the container restarts if it crashes
