apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    [[inputs.kafka_consumer]]
      brokers = ["localhost:9092"]
      topics = ["sensor_topic"]
      group_id = "telegraf-consumer"
      offset = "oldest"
      data_format = "json"

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
      token = "my-secret-token"
      organization = "my-org"
      bucket = "my-bucket"
